# Generated by Django 2.2 on 2020-08-09 19:38

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone_number', models.CharField(max_length=12)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Interval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('singular', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Interval',
                'verbose_name_plural': 'Intervals',
            },
        ),
        migrations.CreateModel(
            name='NizaEmployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Niza Employee',
                'verbose_name_plural': 'Niza Employees',
            },
        ),
        migrations.CreateModel(
            name='NizaJobPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Niza Job Position',
                'verbose_name_plural': 'Niza Jobs positions',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='project_cover')),
                ('time', models.PositiveIntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='niza.Customer')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='niza.NizaEmployee')),
                ('interval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='niza.Interval')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.AddField(
            model_name='nizaemployee',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='niza.NizaJobPosition'),
        ),
        migrations.CreateModel(
            name='CustomerReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('score', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=50)),
                ('comment', models.TextField()),
                ('position', models.CharField(max_length=30)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='niza.Customer')),
            ],
            options={
                'verbose_name': 'Customer Review',
                'verbose_name_plural': 'Cusomter Reviews',
            },
        ),
    ]
