# Generated by Django 2.2 on 2020-09-07 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niza', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='order_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
