# Generated by Django 2.2 on 2020-09-07 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niza', '0004_auto_20200907_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfile',
            name='name',
            field=models.CharField(default='Archivo Niza', max_length=50),
        ),
    ]
