# Generated by Django 2.2 on 2020-09-07 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('niza', '0006_projecttask_done'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projecttask',
            options={'ordering': ['done'], 'verbose_name': 'Project Task', 'verbose_name_plural': 'Project Tasks'},
        ),
    ]
